name: .NET Common Libraries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet package
      run: |
         for f in ./**/*.nupkg
         do
           curl -vX PUT -u "EinsteinsErbe:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/EinsteinsErbe/
         done
      shell: bash
